### ISSUE TITLE
"wrong number of arguments (1 for 0)" after "bundle exec rake db:migrate"

### ISSUE THREAD

**Issue by milos-aleksic** [code-mancers/invoicing#45]
I'm trying to follow the installation guide but I'm not able to go trough the migrate process. After running _bundle exec rails generate invoicing_ everything works as expected, all the respective files are created, but when I try to run _bundle exec rake db:migrate_ only "CreateInvoicingTaxRates:" is migrated, afterwards a **StandardError: wrong number of arguments (1 for 0)** is displayed and rest of migrations aborted.

I'm totally newbie so I'm not sure if I'm doing something wrong... I'm working on Rails 4.2.0.beta4

Let me know if there is any other information I could provide and thanks in advance.

**Comment by iffyuva** [comment]
im testing this gem with rails 4.1, and 4.2 i shall update this issue accordingly.

**Comment by iffyuva** [comment]
im able to run db:migrate. can you check once?

```
opensource/issue-45> br g invoicing
      create  db/migrate/20150112120621_create_invoicing_tax_rates.rb
      create  app/models/invoicing_tax_rate.rb
      create  db/migrate/20150112120622_create_invoicing_ledger_items.rb
      create  app/models/invoicing_ledger_item.rb
      create  db/migrate/20150112120623_create_invoicing_line_items.rb
      create  app/models/invoicing_line_item.rb
bundle exec rails g invoicing  2.30s user 0.39s system 97% cpu 2.757 total
opensource/issue-45> be rake db:migrate
== 20150112120621 CreateInvoicingTaxRates: migrating ==========================
-- create_table(:invoicing_tax_rates)
   -> 0.0019s
== 20150112120621 CreateInvoicingTaxRates: migrated (0.0021s) =================

== 20150112120622 CreateInvoicingLedgerItems: migrating =======================
-- create_table(:invoicing_ledger_items)
   -> 0.0013s
== 20150112120622 CreateInvoicingLedgerItems: migrated (0.0014s) ==============

== 20150112120623 CreateInvoicingLineItems: migrating =========================
-- create_table(:invoicing_line_items)
   -> 0.0012s
== 20150112120623 CreateInvoicingLineItems: migrated (0.0013s) ================

bundle exec rake db:migrate  1.99s user 0.33s system 97% cpu 2.386 total
```

**Comment by iffyuva** [comment]
@milos-aleksic closing this one. please check with latest version of this gem ie 1.0.1 as it supports 4.2.0
