### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by mooreds** [code-mancers/invoicing#50]
Hi folks,

Was wondering if this project is alive.

**Comment by iffyuva** [comment]
hi,
  what do you have on your mind? :)

**Comment by mooreds** [comment]
@iffyuva Sorry, I may have been more blunt than I meant to be.  

I was wondering if this project was still being actively developed, or if it was in maintenance mode?

**Comment by iffyuva** [comment]
@mooreds you are not offensive. yes, currently the project is in maintenance mode. do you have any ideas that you would like to discuss?

**Comment by mooreds** [comment]
@iffyuva I have some ideas, but not much time at the moment.  Thanks for letting me know this project is in maintenance mode.  

I may write up some of my experiences (customizing the invoice generated, extending the invoice model) in the future.
