### ISSUE TITLE
Question : How to handle a payment of a invoice 

### ISSUE THREAD

**Issue by ghost** [code-mancers/invoicing#51]
Hello 

lets say I have made a invoice of 100 euro to customer A 
Now this one is payed by bank.

How to I handle this with this gem.

**Comment by iffyuva** [comment]
hello @rwobben 
  invoicing system is different from payment system. ie you can have these 2 cases:
- you can raise 1 invoice for 100 euros, and customer can pay that invoice in 5 installments, ie payment of 20 euros for 5 times. 
- you can raise 2 invoices for 50, and 70 euros, and customer can pay both the invoices in one shot, ie 1 payment of 120 euros.

in both the cases, whenever money is received, we make an entry into payments table. we call it as `payment note`, its a ledger item, which will have 1 line item, which stores payment amount.

Please let me know if you have any doubts. You can post some code here for more help.

**Comment by rwobben** [comment]
oke, 
Please show me some code for both cases.
So I cannot check with this engine if a invoice is payed or too late. 

and if so, it is easy to implement a sort of invoicing system.

**Comment by thegeorgeous** [comment]
Closing this issue.
